# Variable 'deployment_token' was defined in the Variables tab
trigger:
  branches:
    include:
    - refs/heads/master

jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-latest

  steps:
  - checkout: self
    clean: true

  - task: Npm@1
    displayName: npm install
    inputs:
      workingDir: front-end/
      verbose: false

  - task: Bash@3
    displayName: running tests
    inputs:
      targetType: inline
      script: npm run test
      workingDirectory: front-end/
      
  - task: AzureStaticWebApp@0
    displayName: Deploy to Static Web App
    inputs:
      app_location: front-end
      output_location: build
      skip_app_build: false
      skip_api_build: false
      verbose: false
      azure_static_web_apps_api_token: $(deployment_token)
