pool:
  name: Azure Pipelines
  demands: maven

steps:
  - task: Maven@3
    displayName: "Maven pom.xml"
    inputs:
      mavenPomFile: "$(Parameters.mavenPOMFile)"
      jdkVersionOption: 1.11

  - task: Maven@3
    displayName: "Build Docker image"
    inputs:
      mavenPomFile: "back-end/pom.xml"
      goals: "spring-boot:build-image"
      publishJUnitResults: false
      jdkVersionOption: 1.11

  - task: Docker@2
    displayName: "Push Docker image"
    inputs:
      containerRegistry: backendContainerRegistry
      repository: backend
      command: push
      tags: latest
